version: '3.4'

services:
  blazorapp:
    build: .
    ports:
      - "8000:80"   # Map HTTP traffic
      - "5001:443"  # Map HTTPS traffic

    volumes:
      - data_protection_keys:/root/.aspnet/DataProtection-Keys
      - ${HOME}/.aspnet/https:/https:ro  # Mount the certificate directory

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1 # Added - For Debugging
      - ASPNETCORE_URLS=https://+443;http://+80
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<your-password>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

volumes:
  data_protection_keys: